FROM nvidia/cuda:12.8.1-cudnn-runtime-ubuntu22.04

RUN apt update && apt install -y cuda-toolkit-12-8 nano wget curl unzip git build-essential python3-dev

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
