[project]
name = "sfcomputerl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beartype>=0.20.2",
    "pyyaml>=6.0.2",
]
